" Author: Alexandre Alencar
" alencardev@gmail.com
" I highly recommend you to copy whatever you want from this vimrc file,
" though it was customized for my needs, so keep that in mind.

" PLUGINS MANAGEMENTS {{{1

" --------------- Vundle Inicialization --------------- {{{2
" enter the current millenium
set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim' " }}}2

" --------------- List of Plugins --------------- {{{2
" Navigation
Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-vinegar.git'
Plugin 'christoomey/vim-tmux-navigator'
"Plugin 'scrooloose/nerdtree'
"Plugin 'bling/vim-bufferline'

" Programming
Plugin 'tpope/vim-fugitive' " git integration
Plugin 'gregsexton/gitv'    " display commits
Plugin 'pangloss/vim-javascript'
" Plugin 'ternjs/tern_for_vim'
Plugin 'leafgarland/typescript-vim'
Plugin 'SirVer/ultisnips'
Plugin 'jiangmiao/auto-pairs'
Plugin 'sjl/gundo.vim'
Plugin 'tpope/vim-surround'
"Plugin 'vim-syntastic/syntastic'
Plugin 'majutsushi/tagbar'
Plugin 'w0rp/ale' 

" Styling
Plugin 'altercation/vim-colors-solarized'
Plugin 'morhetz/gruvbox'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
" }}}2

"  --------------- Plugins Config --------------- {{{2
" Ultisnips
let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"
let g:UltiSnipsEditSplit='vertical'
let g:UltiSnipsSnippetsDir='~/.vim/UltiSnips'

" Ctrl-P
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_custom_ignore = 'node_modules\|git\|.*.map\|.*.js\|.*.spec.ts'

" vinegar
let g:netrw_liststyle = 0
let g:netrw_list_hide = '^.*\.map$,^.*\.spec\..*$'

" airline
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" syntastic
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 0
let g:syntastic_check_on_wq = 0

" tagbar
let g:tagbar_ctags_bin = '/usr/local/Cellar/ctags/5.8_1/bin/ctags'

" autopairs
let g:AutoPairsFlyMode = 1

" All of your Plugins must be added before the following line
call vundle#end()            " required }}}2
" }}}1

"  GENERAL CONFIGURATION {{{1

" --------------- Misc --------------- {{{2
set ttyfast " faster redraw
set termguicolors

" make vim try to detect file types and load plugins for them
filetype on
filetype plugin indent on
filetype indent on

" turn on syntax highlighting
syntax enable
syntax on

set hidden                      " make vim use hidden buffer more liberally
set noswapfile                  " no swap files
set autoread                    " reload files changed outside vim
set encoding=utf-8              " encoding is utf 8
set nobackup
runtime macros/matchit.vim      " enable matchit plugins which ships with vim and enhances '%'
set dict+=/usr/share/dict/words " dictionary
au FileType * set fdm=syntax " }}}2
au FileType html set fdm=indent " }}}2

" --------------- UI --------------- {{{2
set scrolloff=3                 " minimal number of lines to keep above and bellow the cursor
set number                      " display line number
set relativenumber              " display the line number relative to the line with the cursor
set showcmd                     " show last command entered in the bottom bar"
set wildmenu                    " visual autocomplete for command menu
set lazyredraw                  " redraw only when need to
set laststatus=2                " always shows the file name at the bottom }}}2

"  --------------- Editing --------------- {{{2
set backspace=indent,eol,start

" toggle invisible characters
set list
set listchars=tab:→\ ,trail:⋅,extends:❯,precedes:❮
set showbreak=↪


set textwidth=80
" }}}2

" --------------- Searching --------------- {{{2
set incsearch       " search as characters are entered
set hlsearch        " highlight matches
set ignorecase      " the case of normal letters is ignored.
set smartcase       " case-sensitive searching only when a capital letter appears" }}}2

" --------------- Folding --------------- {{{2
"set foldcolumn=4                " display folding level on left bar
set foldlevelstart=3            " open most folds by default }}}

"  --------------- Indentation --------------- {{{2
set autoindent      " autoindent based on line above, works most of the time
set smartindent     " smarter indent for C-like languages
" }}}2

"  --------------- Tabs --------------- {{{2
set expandtab       " always use spaces
set tabstop=4       " how many spaces a <Tab> counts for
set shiftwidth=4    " how many spaces when identing
set softtabstop=4   " number of tabs when in insert mode

" tab setup for html files
au Filetype html setlocal shiftwidth=2 tabstop=2 softtabstop=2
au Filetype typescript setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2
au Filetype css setlocal expandtab shiftwidth=2 tabstop=2 softtabstop=2
" }}}2

"  --------------- Style --------------- {{{2
" For solarized plugin (color scheme)
" https://github.com/altercation/vim-colors-solarized
syntax enable
set background=dark
colorscheme gruvbox
" }}}2
" }}}1

"  MAPPINGS {{{1
let mapleader = ","
nnoremap ; :
nnoremap : ;

" --------------- Good Habits--------------- {{{2
inoremap <c-c> <c-o>:throw 'use c-[ instead of c-c'<cr>
inoremap <ESC> <C-o>:throw 'Use jk instead of ESC'<CR>
nnoremap zo :throw 'Use "space" to open/close folds'<CR>
nnoremap zc :throw 'Use "space" to open/close folds'<CR>
nnoremap $ :throw 'Use "E" instead of $'<CR>
nnoremap ^ :throw 'Use "B" instead of ^'<CR>
inoremap jk <ESC>
" }}}2

"  --------------- Plugins --------------- {{{2
"  UltiSnips
noremap <leader>u :UltiSnipsEdit<CR>

" vim-fugitive
noremap <leader>gc :Gcommit<CR>
noremap <leader>gd :Gdiff<CR>
noremap <leader>gs :Gstatus<CR>
noremap <leader>gp :Gpush<CR>
noremap <leader>gl :Glog<CR>
noremap <leader>gg :Ggrep 
noremap <leader>gm :Gmove 

" vinegar
noremap § :Explore<CR>

" Gundo
nnoremap <leader>u :GundoToggle<CR>

" }}}2

"  --------------- Editing  --------------- {{{2
noremap <leader>a ggVG
vmap <leader>y "*y
vmap <leader>p "*p
nnoremap gV `[v`]
" }}}2

" --------------- Searching --------------- {{{2
nnoremap <leader><space> :nohlsearch<CR> }}}2

" --------------- Folding --------------- {{{2
nnoremap <space> za         " open/close folds }}}2

"  --------------- Navigation  --------------- {{{2
" moving up and down as expected
nnoremap j gj
nnoremap k gk

" move to beginning and end of line
nnoremap B ^
nnoremap E $

" scroll the viewport 3x faster
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" quickfix list
noremap ]q :cn<CR>
noremap [q :cp<CR>
" }}}2

" --------------- Files  --------------- {{{2
noremap <leader>w :w<CR> 
noremap <leader>q :q<CR>
noremap <leader>Q :q!<CR>

" vim
noremap <leader>ev :e $MYVIMRC<CR>
noremap <leader>sv :source $MYVIMRC<CR>

" tmux
noremap <leader>et :e $TMUXCONF<CR>
noremap <leader>es :e ~/.tmux-sessions/<CR>

" bash
noremap <leader>eb :e ~/.bashrc<CR>

" journal
noremap <leader>j :e ~/journal<CR>

" todo
noremap <leader>k :e ~/TODO<CR>
" }}}2

"  --------------- Buffers --------------- {{{2
" switch to next and previous buffers
noremap <leader>l :ls<CR>
noremap ]b :bn<CR>
noremap [b :bp<CR>
noremap ]B :bl<CR>
noremap [B :bf<CR>
noremap <leader>d :bd<CR>
noremap <leader>. <C-^>
" }}}2

"  --------------- Panes --------------- {{{2
" swith between panes
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" maps to split window
noremap <leader>\ :vsplit<CR>
noremap <leader>- :split<CR>
" }}}2

"  --------------- Development --------------- {{{2
"  WebDev
nnoremap <leader>oc :!open -a /Applications/Google\ Chrome.app %<CR><CR>
nnoremap <leader>os :!open -a /Applications/Safari.app %<CR><CR>

" Angular 2
nnoremap <leader>tt :tabnew % <bar> :vsplit %.component.css <bar> :sfind *.html<CR> " }}}2

"  --------------- Style --------------- {{{2
nnoremap <leader>bd :set background=dark<CR>
nnoremap <leader>bl :set background=light<CR>
" }}}2
" }}}1

"  FUNCTIONS {{{1
" popolates the args list with the quickfix files
command! -nargs=0 -bar Qargs execute 'args ' . QuickfixFilenames()
function! QuickfixFilenames()
  " Building a hash ensures we get each buffer only once
  let buffer_numbers = {}
  for quickfix_item in getqflist()
    let buffer_numbers[quickfix_item['bufnr']] = bufname(quickfix_item['bufnr'])
  endfor
  return join(values(buffer_numbers))
endfunction
" }}}1

" vim:foldmethod=marker:foldlevel=0
